### ISSUE TITLE
More directory structure is needed

### ISSUE THREAD

**Issue by NightMachinery** [kokizzu/svelte-mpa#6]
Coming from the official svelte template, I miss having a `public` directory for assets.

And the output of this template is just exported in the git root, which is awful. Indeed, the deployment script does:
```
rsync -vvritn $DRY_RUN \
  --exclude='_*' \
  --exclude='.*' \
  --exclude='*.svelte' \
  --exclude='*.sh' \
  --exclude='*.md' \
  --exclude='package*.json' \
  --exclude='tsconfig.json' \
  --exclude='svelte.config.js' \
  --exclude='build.js' \
  --exclude='node_modules' \
  --include='*.ico' \
  --include='*.js' \
  --include='*.html' \
  --include='*.css' \
 . $SERVER:/var/www/html/
```

This will miss assets that are, e.g., `.png`. If the output was put in a `dist` directory, things would be much better.

Also, these files have been manually (!!) ignored in `.gitignore`, which is a terrible solution:
```
# generated files

index.html
page1/subpage.html
page1/subpage3/index.html
page2/index.html
```

compared to:
```
dist/
```

**Comment by kokizzu** [comment]
you can just create `dist/` as needed after `degit` as your own preference of project structure, 
then you just only need to exclude the `*.svelte` file when doing rsync or adding to container for deployment

**Comment by NightMachinery** [comment]
@kokizzu How do I add `dist/`? Do you mean like a `mkdir -p dist/`, or is there an option that will actually generate the files inside the specified directory?

**Comment by kokizzu** [comment]
yup just `mkdir`, each project can be customized as needed

**Comment by kokizzu** [comment]
that gitignore is for this project, usually after `degit`, all generated `.html` also comitted, not gitignored
